# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
# Abdelkarim Guettaf <gkraim@gmail.com>, 2015.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2015-05-09 17:39+0200\n"
"PO-Revision-Date: 2015-05-09 13:30+0100\n"
"Last-Translator: Abdelkarim Guettaf <gkraim@gmail.com>\n"
"Language-Team: Arabic <wahaproject@gmail.com>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=6; plural= n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 "
"&& n%100<=10 ? 3 : n%100>=11 && n%100<=99 ? 4 : 5;\n"
"X-Generator: Gtranslator 2.91.6\n"

#: ../usr/lib/ddm/ddm.py:46 ../usr/lib/ddm/main.py:26
#: ../usr/share/kde4/services/kcm_device_driver_manager.desktop.in.h:1
#: ../usr/share/applications/ddm.desktop.in.h:1
msgid "Device Driver Manager"
msgstr "مدير تعريف الأجهزة"

#: ../usr/lib/ddm/ddm.py:47 ../usr/lib/ddm/ddm.py:155
msgid "Install"
msgstr "التثبيت"

#: ../usr/lib/ddm/ddm.py:48
msgid "Help"
msgstr "مساعدة"

#: ../usr/lib/ddm/ddm.py:49
msgid "Quit"
msgstr "خروج"

#: ../usr/lib/ddm/ddm.py:104
msgid "No internet connection"
msgstr "لا يوجد اتصال بالإنترنت"

#: ../usr/lib/ddm/ddm.py:105
msgid ""
"You need an internet connection to install the additional software.\n"
"Please, connect to the internet and try again."
msgstr ""
"تحتاج لاتصال بالإنترنت لتثبيت البرامج الإضافية.\n"
"من فضلك، اتّصل بالإنترنت وحاول مرة أخرى."

#: ../usr/lib/ddm/ddm.py:155
msgid "Device"
msgstr "الجهاز"

#: ../usr/lib/ddm/ddm.py:171
msgid "Remove kernel"
msgstr "إزالة النواة"

#: ../usr/lib/ddm/ddm.py:172
msgid ""
"You cannot remove a booted kernel.\n"
"Please, boot another kernel and try again."
msgstr ""
"لا يمكنك إزالة النواة المستخدمة حاليا.\n"
"من فضلك، حاول بعد إعادة التشغيل بنواة أخرى."

#: ../usr/lib/ddm/ddm.py:193
msgid "Hardware scan"
msgstr "تفحص الأجهزة"

#: ../usr/lib/ddm/ddm.py:197
msgid "There are no available drivers for your hardware:"
msgstr "لا توجد تعريفات متوفرة لعتادك:"

#: ../usr/lib/ddm/ddm.py:203
msgid "DDM did not find any supported hardware."
msgstr "لم يعثر مدير التعريف على أي عتاد مدعوم."

#: ../usr/lib/ddm/ddm.py:251
msgid "Saved"
msgstr "حُفِظ"

#: ../usr/lib/ddm/ddm.py:252
msgid "You will need to restart your system."
msgstr "ستحتاج لإعادة تشغيل نظامك."

#: ../usr/lib/ddm/ddm.py:456
msgid "PAE capable system"
msgstr "النظام يدعم PAE"

#: ../usr/lib/ddm/ddm.py:558
msgid ""
"There was an error during the installation.\n"
"Please, run 'sudo apt-get -f install' in a terminal.\n"
"Visit our forum for support: http://forums.solydxk.com"
msgstr ""
"حدث خطأ أثناء التثبيت.\n"
"من فضلك، شغّل 'sudo apt-get -f install' في الطرفية.\n"
"يمكنك زيارة منتدانا للحصول على الدعم: http://forums.solydxk.com"

#: ../usr/lib/ddm/ddm.py:567
msgid "The software has been successfully installed."
msgstr "تم تثبيت البرنامج بنجاح."

#: ../usr/lib/ddm/main.py:27
msgid ""
"Device Driver Manager cannot be started in a live environment\n"
"You can use the --force argument to start DDM in a live environment"
msgstr ""
"لا يمكن تشغيل مدير تعريف الأجهزة في بيئة حية\n"
"يمكنك استخدام المعامل --force لبدء DDM في بيئة حية"

#: ../usr/lib/ddm/main.py:69
msgid "Unexpected error"
msgstr "خطأ غير متوقع"

#: ../usr/lib/ddm/main.py:70
msgid ""
"<b>DDM has failed with the following unexpected error. Please submit a bug "
"report!</b>"
msgstr ""
"<b>واجه DDM خطأ غير متوقع، من فضلك أرسل تقريرا عن وجود علّة!</b>"
